"""마이그레이션이 실제로 돌고, 모델과 어긋나지 않는지 본다.

## 왜 따로 필요한가 — 스위트가 마이그레이션을 건너뛰고 있다

`test_auth.py` · `test_usage_tracking.py` 는 `Base.metadata.create_all()` 로 표를
만든다. 빠르고 DB 를 안 띄워도 되지만, **그 경로는 `migrations/versions/*` 를 한 줄도
읽지 않는다.** 그래서 마이그레이션이 모델과 어긋나거나 아예 깨져 있어도 스위트는
전부 초록이고, 고장은 `alembic upgrade head` 를 처음 돌리는 **배포 시점**에 드러난다.

이 저장소가 반복해 잡아 온 실패 양식과 같은 모양이다 — 게이트는 100% 인데 산출물이
제품에 안 닿는다. 계정층은 특히 그 위험이 크다: 2026-08-26 에 마이그레이션을 만들고
2026-08-27 에 API 를 붙였는데, 그 사이 `alembic upgrade head` 가 실행된 적이 없었다
(2026-08-27 확인 — 첫 실행에서 통과했고, 그 사실을 여기 고정한다).

## SQLite 로 재는 것의 한계

프로덕션은 Postgres 다. 여기서 SQLite 를 쓰는 이유는 CI 가 DB 를 안 띄우기 때문이고,
모델이 애초에 그걸 전제로 설계돼 있다(`models/auth.py` 머리말 — UUID 를 문자열로 저장).
따라서 이 테스트가 잡는 것은 **마이그레이션↔모델 드리프트와 실행 가능성**이지
Postgres 고유 동작이 아니다. 그 구분을 흐리지 않으려고 여기 적어 둔다.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.auth import ApiKey, AuditLog, Membership, Org, User
from app.services.usage import ACCESS_PREFIX, usage_summary


def _backend_dir() -> Path:
    """apps/backend — alembic.ini 와 migrations/ 가 사는 곳."""
    return Path(__file__).resolve().parents[1]


def _alembic_config(url: str) -> Config:
    """`alembic.ini` 를 그대로 쓰되 URL 만 갈아끼운다.

    `migrations/env.py` 는 URL 을 `settings.database_url` 에서만 읽는다(단일 출처).
    그 규약을 여기서 깨지 않으려고 ini 를 덮어쓰는 대신 settings 를 갈아끼운다 —
    호출부가 monkeypatch 로 처리한다.
    """
    cfg = Config(str(_backend_dir() / "alembic.ini"))
    cfg.set_main_option("script_location", str(_backend_dir() / "migrations"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


@pytest.fixture()
def migrated_url(tmp_path, monkeypatch) -> str:
    """`alembic upgrade head` 를 실제로 돌린 빈 DB 의 URL."""
    url = f"sqlite:///{tmp_path / 'acct.db'}"
    monkeypatch.setattr(settings, "database_url", url, raising=False)
    command.upgrade(_alembic_config(url), "head")
    return url


def test_migration_runs_and_creates_the_account_tables(migrated_url):
    """마이그레이션이 실행되고 계정층 5개 표를 만든다."""
    tables = set(inspect(create_engine(migrated_url)).get_table_names())
    assert {"orgs", "users", "memberships", "api_keys", "audit_log"} <= tables
    # 버전 표가 없으면 다음 마이그레이션이 처음부터 다시 돈다
    assert "alembic_version" in tables


def test_migration_matches_the_models(migrated_url):
    """마이그레이션 == 모델. 드리프트가 있으면 `alembic check` 가 터진다.

    여기가 이 파일의 핵심이다 — 누가 `models/auth.py` 에 컬럼을 추가하고
    마이그레이션을 안 만들면, `create_all` 기반 테스트는 전부 통과하지만
    배포된 DB 에는 그 컬럼이 없다. 그 상태를 여기서 잡는다.
    """
    try:
        command.check(_alembic_config(migrated_url))
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "마이그레이션이 모델과 어긋난다 — `alembic revision --autogenerate` 로 "
            f"새 리비전을 만들 것.\n{exc}")


def test_migrated_schema_serves_the_real_write_path(migrated_url):
    """마이그레이션이 만든 표 위에서 실제 ORM 쓰기·집계가 돈다.

    표가 생겼다는 것과 제품 코드가 그 표를 쓸 수 있다는 것은 다른 주장이다.
    가입(조직+사용자+멤버십) → 키 발급 → 접근 기록 → 사용량 집계까지 한 번 태운다.
    """
    engine = create_engine(migrated_url)
    with Session(engine) as db:
        org = Org(name="파일럿 자산운용")
        user = User(email="pilot@example.com", hashed_password="x" * 20)
        db.add_all([org, user])
        db.flush()
        db.add_all([
            Membership(org_id=org.id, user_id=user.id, role="admin"),
            ApiKey(org_id=org.id, name="연동용", key_hash="hash-" + "y" * 20),
            AuditLog(org_id=org.id, user_id=user.id,
                     action=f"{ACCESS_PREFIX}api_key", detail="/api/v1/commercial-districts/"),
        ])
        db.commit()

        org_id = org.id          # commit 이 인스턴스를 만료시키므로 세션 안에서 집는다
        summary = usage_summary(db, days=30)

    assert summary["active_orgs"] == 1, summary
    assert summary["total_accesses"] == 1, summary
    assert summary["by_org"] == {org_id: 1}, summary


def test_usage_window_excludes_old_records(migrated_url):
    """집계 창(window) 밖의 기록은 안 센다.

    `usage_summary` 가 tz-aware 기준시각으로 비교하는데 SQLite 는 tz 를 안 실어
    보관한다. 창이 사실상 무한대가 되면 `active_orgs` 가 영원히 안 떨어져서
    "파일럿이 죽었다"를 관측할 수 없게 된다 — 지표가 고장을 가리는 모양이라 고정한다.
    """
    engine = create_engine(migrated_url)
    with Session(engine) as db:
        org = Org(name="옛 파일럿")
        db.add(org)
        db.flush()
        db.add(AuditLog(org_id=org.id, action=f"{ACCESS_PREFIX}api_key", detail="/old",
                        created_at=datetime.now(timezone.utc) - timedelta(days=90)))
        db.commit()

        assert usage_summary(db, days=30)["active_orgs"] == 0
        assert usage_summary(db, days=365)["active_orgs"] == 1
